#!/usr/bin/env bash
##############################################################################
# generate-inventory.sh — Create Ansible inventory from Terraform outputs
#
# Run after `terraform apply` to generate ansible/inventory.ini
# with the public IPs of the Hetzner Cloud worker machines.
#
# Usage:
#   cd terraform && ./generate-inventory.sh
#   # or from project root:
#   bash terraform/generate-inventory.sh
##############################################################################
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

cd "$SCRIPT_DIR"

echo "==> Reading Terraform outputs..."

WORKER_PUBLIC=$(terraform output -json worker_public_ips)
WORKER_NAMES=$(terraform output -json worker_names)
WORKER_PORT=$(terraform output -raw worker_port)
DEPLOY_DIR=$(terraform output -raw deploy_dir)
DENO_VERSION=$(terraform output -raw deno_version)

WORKER_COUNT=$(echo "$WORKER_PUBLIC" | python3 -c "import sys,json; print(len(json.load(sys.stdin)))")

if [[ "$WORKER_COUNT" -eq 0 ]]; then
  echo "ERROR: No workers found in Terraform state. Did you run 'terraform apply'?" >&2
  exit 1
fi

INVENTORY_FILE="$PROJECT_DIR/ansible/inventory.ini"

echo "==> Generating inventory for $WORKER_COUNT worker(s)..."

cat > "$INVENTORY_FILE" <<EOF
# Auto-generated by terraform/generate-inventory.sh — do not edit manually.
# Re-run: cd terraform && ./generate-inventory.sh

[workers]
EOF

for i in $(seq 0 $((WORKER_COUNT - 1))); do
  NAME=$(echo "$WORKER_NAMES" | python3 -c "import sys,json; print(json.load(sys.stdin)[$i])")
  PUB_IP=$(echo "$WORKER_PUBLIC" | python3 -c "import sys,json; print(json.load(sys.stdin)[$i])")
  echo "${NAME}  ansible_host=${PUB_IP}  worker_port=${WORKER_PORT}" >> "$INVENTORY_FILE"
done

cat >> "$INVENTORY_FILE" <<EOF

[workers:vars]
ansible_user=root
ansible_ssh_common_args=-o StrictHostKeyChecking=no
deploy_dir=${DEPLOY_DIR}
worker_listen=0.0.0.0
worker_port=${WORKER_PORT}
deno_bin=deno
deno_version=${DENO_VERSION}
EOF

echo "==> Inventory written: $INVENTORY_FILE"
echo ""
cat "$INVENTORY_FILE"
echo ""
echo "==> Next steps:"
echo "  ansible-playbook -i ansible/inventory.ini ansible/deploy-workers.yml"
